apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    run: backend-user
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
    protocol: TCP
  selector:
    run: backend-user